export * from './get-all'
export * from './get-count-active'
export * from './get-department-distribution'
export * from './get-subject-coverage'
export * from './get-status-breakdown'
export * from './post-teacher'
export * from './put-teacher'
export * from './delete-teacher'
